### ISSUE TITLE
Migrating to ESM

### ISSUE THREAD

**Issue by TomerAberbach** [adonisjs/repl#3]
Hey! :wave: 

I'm the maintainer of [`parse-imports`](https://github.com/TomerAberbach/parse-imports). I'm going to publish v1.0.0 soon and migrate to ESM-only (i.e. `"type": "module"`) without publishing a CJS version of the package.

I noticed that your package accounts for most usage of `parse-imports`, but also that it does not specify `"type": "module"`, so you would encounter some issues if you try to upgrade. You have a few options:
1. Not upgrading to v1.0.0
2. Upgrading to v1.0.0, still targeting CJS, and using dynamic import to import `parse-imports` instead of `require` ([you can't `require` ESM modules](https://nodejs.org/api/esm.html#esm_require))
3. Upgrading to v1.0.0 and targeting ESM (in this scenario you can import `parse-imports` normally)

I would recommend eventually getting to 3 because [that's the direction the ecosystem is moving](https://github.com/sindresorhus/meta/discussions/15).

Anyways, just thought I'd give you a heads up! Feel free to close this issue after you read it

**Comment by thetutlage** [comment]
Hello @TomerAberbach 

Thanks for the heads up! I think moving to ESM will be a big change for me right now, consider the entire framework has to move to ESM. So I will stick to `v1.0.0`.

Appreciate you reaching out :)

**Comment by TomerAberbach** [comment]
No problem :)

And sounds good! (I assume you mean you'll stick to `v0.0.5`, the current version)

**Comment by thetutlage** [comment]
Closing, as this something we will tackle later :)
