### ISSUE TITLE
feat: customization of REPL server properties

### ISSUE THREAD

**Issue by dec0dOS** [adonisjs/repl#8]
The current implementation of the REPL server does not permit alterations to the default prompt or redirection of input and output, as observed in the existing codebase:
https://github.com/adonisjs/repl/blob/5951b78a91fd8eaf922b3dff1b46cf954eeb2574/src/repl.ts#L363-L376

To enhance flexibility and user control, I propose the introduction of a functionality that allows users to override the options supplied to the Node.js `startRepl` method. The proposed change is illustrated below:
```typescript
  start(options) {
    console.log('')
    this.notify('Type ".ls" to a view list of available context methods/properties')

    this.server = startRepl({
      prompt: `> ${this.#compiler?.supportsTypescript ? '(ts) ' : '(js) '}`,
      input: process.stdin,
      output: process.stdout,
      terminal: process.stdout.isTTY && !Number.parseInt(process.env.NODE_NO_READLINE!, 10),
      useGlobal: true,
      ...options,
    })
```

This modification would grant users greater control over the REPL environment. Thanks!

**Comment by thetutlage** [comment]
Can you please create a PR for the same?

**Comment by thetutlage** [comment]
Hey, I have added support to accept the options via Repl class constructor. Lemme know if that works for you.

https://github.com/adonisjs/repl/releases/tag/v4.0.0-10

**Comment by dec0dOS** [comment]
Thanks, it's working as expected now!
